// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7uOa27wXLTjzDQzq0ftwsXTCa5mwBNx0',
    appId: '1:617322943880:web:19553554adb2afdf8ed63d',
    messagingSenderId: '617322943880',
    projectId: 'quote-app-d6bf4',
    authDomain: 'quote-app-d6bf4.firebaseapp.com',
    storageBucket: 'quote-app-d6bf4.appspot.com',
    measurementId: 'G-H477Z6Z5JB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALuV3iJgSFeBwHoRIMlk3eHcchrUCrAT0',
    appId: '1:617322943880:android:46efd1a06072e2568ed63d',
    messagingSenderId: '617322943880',
    projectId: 'quote-app-d6bf4',
    storageBucket: 'quote-app-d6bf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkyII0K-QkoG2Z8NHMzxmPlg9CnP4CQEE',
    appId: '1:617322943880:ios:47e3d06c5a83c38a8ed63d',
    messagingSenderId: '617322943880',
    projectId: 'quote-app-d6bf4',
    storageBucket: 'quote-app-d6bf4.appspot.com',
    iosClientId: '617322943880-8nqft1e1lp466buqqap3sdksbc911tvf.apps.googleusercontent.com',
    iosBundleId: 'com.example.quotes',
  );
}
